/*  {{ .Module }}.v was generated by jtframe mmr.
    Do not edit this generated file directly.
    Edit cfg/mmr.yaml or modules/jtframe/hdl/inc/mmr.v instead.
    Do not add generated *_mmr.v files to git. */
{{ $is_16bit := 0 }}{{ if eq .Dw 16 }}{{ $is_16bit = 1 }}{{ end }}
module {{ .Module }}(
    input             rst,
    input             clk,

    input             cs,
    input       [{{.AMSB}}:{{$is_16bit}}] addr,
    input             rnw,
    input       [{{ sub .Dw 1 }}:0] din, {{ if not .Read_only }}
    output reg  [{{ sub .Dw 1 }}:0] dout, {{- end }}{{ if $is_16bit }}
    input       [1:0] dsn,
    {{- end }}
    {{ range .Regs }}
    output {{if .IsEvent }}reg  {{else}}{{if eq .Dw 1}}     {{else}}[{{ sub .Dw 1 }}:0]{{end}}{{ end }} {{ .Name }},
    {{- end }}

    // IOCTL dump
    input      [{{.AMSB}}:0] ioctl_addr,
    output reg [7:0] ioctl_din,
    // Debug
    input      [7:0] debug_bus,
    output reg [7:0] st_dout
);

localparam SIZE={{.Size}};
parameter SIMFILE="rest.bin",
          SEEK=0;
parameter [SIZE*8-1:0] INIT=0; // from high to low regs {mmr[3],mmr[2],mmr[1],mmr[0]}


reg  [ 7:0] mmr[0:SIZE-1];
integer     i;
{{ range .Regs }}{{ if not .IsEvent }}{{ $chunks := .Chunks }}
assign {{.Name}} = {
{{- range $idx, $chunk := $chunks }}
    mmr[{{$chunk.Byte}}][{{if eq $chunk.Msb $chunk.Lsb}}{{$chunk.Msb}}{{else}}{{$chunk.Msb}}:{{$chunk.Lsb}}{{end}}]{{ if lt (add1 $idx) (len $chunks) }},{{end}}
{{- end }}
    };
{{end}}{{ end }}

always @(posedge clk) begin
    if( rst ) begin
        // INIT is used unconditionally so simulation matches synthesis.
        // The old SIMFILE path ($fopen/$fread in an initial block) was
        // never populated by any core and crashed the sim tool.
        for(i=0;i<SIZE;i=i+1) mmr[i] <= INIT[i*8+:8];
        {{ range .Regs }}{{ if .IsEvent }}
        {{.Name}} <= 0; {{ end }}{{- end }}{{ if not .Read_only }}
    dout <= 0; {{- end }}
    end else begin{{ range .Regs }}{{ if .IsEvent }}
        {{.Name}} <= 0; {{ end }}{{- end }}{{ if not .Read_only }}{{ if $is_16bit }}
        dout      <= {mmr[{addr,1'b1}],mmr[{addr,1'b0}]};{{else}}
        dout      <= mmr[addr];{{end}}{{- end }}
        st_dout   <= mmr[debug_bus[{{.AMSB}}:0]];
        ioctl_din <= mmr[ioctl_addr];
        if( cs & ~rnw ) begin{{ if $is_16bit }}
            if(!dsn[0]) mmr[{addr,1'b0}]<=din[ 7:0];
            if(!dsn[1]) mmr[{addr,1'b1}]<=din[15:8];{{else}}
            mmr[addr]<=din;{{end}}
        end{{ range .Regs }}{{ if .IsEvent }}
        if({{.EventCond}}) {{.Name}} <= 1;{{ end }}{{- end }}
        i = 0; // for Quartus linter
    end
end

// SIMFILE/mmr_init loading via $fopen/$fread removed -- segfaulted the
// sim tool on this Windows toolchain regardless of mechanism (see
// comment on the reset always-block above). SIMFILE/SEEK parameters
// kept for interface compatibility but are now unused.

endmodule
