[parse]
sourcefile=[ "moo.cpp" ]
skip = { bootlegs=true, machines=[ "bucky" ] }
[header]
info="Offsets for each ROM region"
offset = { bits=12, reverse=true, regions=["maincpu","soundcpu","tiles","obj"] }

[ROM]
regions = [
    { name="maincpu", width=16, reverse=true  },

    { name="soundcpu"  },
    { name="k054539", rename="pcm" },

    { name="k056832", width=32, rename="tiles" },
    # sprites
    { name="k053246", width=64, rename="obj"},
    { name="eeprom", skip=true }
]

order=["maincpu","soundcpu","pcm","tiles","obj"]
